CREATE DATABASE spotify_db;
USE spotify_db;

CREATE TABLE MEDIA_FILES (
    MediaID INT PRIMARY KEY AUTO_INCREMENT,
    URL VARCHAR(255),
    Format VARCHAR(20),
    Quality VARCHAR(20),
    Type ENUM('Audio', 'Video'),
    Duration INT
) ENGINE=InnoDB;

CREATE TABLE USERS (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) UNIQUE,
    Email VARCHAR(100) UNIQUE,
    PasswordHash VARCHAR(255),
    SubscriptionType ENUM('Free', 'Premium'),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE USER_SETTINGS (
    UserID INT PRIMARY KEY,
    PreferredMode ENUM('Auto', 'AudioOnly', 'Video'),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
) ENGINE=InnoDB;

CREATE TABLE ARTISTS (
    ArtistID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100),
    Country VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE ALBUMS (
    AlbumID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(100),
    ReleaseDate DATE,
    ArtistID INT,
    FOREIGN KEY (ArtistID) REFERENCES ARTISTS(ArtistID)
) ENGINE=InnoDB;

CREATE TABLE SONGS (
    SongID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(100),
    AlbumID INT,
    FOREIGN KEY (AlbumID) REFERENCES ALBUMS(AlbumID)
) ENGINE=InnoDB;

CREATE TABLE SONG_MEDIA (
    SongID INT,
    MediaID INT,
    PRIMARY KEY (SongID, MediaID),
    FOREIGN KEY (SongID) REFERENCES SONGS(SongID),
    FOREIGN KEY (MediaID) REFERENCES MEDIA_FILES(MediaID)
) ENGINE=InnoDB;

CREATE TABLE PODCASTS (
    PodcastID INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(150),
    Description TEXT,
    Language VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE PODCAST_HOSTS (
    HostID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE PODCAST_HOST_MAP (
    PodcastID INT,
    HostID INT,
    PRIMARY KEY (PodcastID, HostID),
    FOREIGN KEY (PodcastID) REFERENCES PODCASTS(PodcastID),
    FOREIGN KEY (HostID) REFERENCES PODCAST_HOSTS(HostID)
) ENGINE=InnoDB;

CREATE TABLE EPISODES (
    EpisodeID INT PRIMARY KEY AUTO_INCREMENT,
    PodcastID INT,
    Title VARCHAR(150),
    ReleaseDate DATE,
    FOREIGN KEY (PodcastID) REFERENCES PODCASTS(PodcastID)
) ENGINE=InnoDB;

CREATE TABLE EPISODE_MEDIA (
    EpisodeID INT,
    MediaID INT,
    PRIMARY KEY (EpisodeID, MediaID),
    FOREIGN KEY (EpisodeID) REFERENCES EPISODES(EpisodeID),
    FOREIGN KEY (MediaID) REFERENCES MEDIA_FILES(MediaID)
) ENGINE=InnoDB;

CREATE TABLE PLAYLISTS (
    PlaylistID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    Name VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
) ENGINE=InnoDB;

CREATE TABLE PLAYLIST_SONGS (
    PlaylistID INT,
    SongID INT,
    PRIMARY KEY (PlaylistID, SongID),
    FOREIGN KEY (PlaylistID) REFERENCES PLAYLISTS(PlaylistID),
    FOREIGN KEY (SongID) REFERENCES SONGS(SongID)
) ENGINE=InnoDB;

CREATE TABLE PLAYLIST_EPISODES (
    PlaylistID INT,
    EpisodeID INT,
    PRIMARY KEY (PlaylistID, EpisodeID),
    FOREIGN KEY (PlaylistID) REFERENCES PLAYLISTS(PlaylistID),
    FOREIGN KEY (EpisodeID) REFERENCES EPISODES(EpisodeID)
) ENGINE=InnoDB;

CREATE TABLE LIKED_SONGS (
    UserID INT,
    SongID INT,
    PRIMARY KEY (UserID, SongID),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    FOREIGN KEY (SongID) REFERENCES SONGS(SongID)
) ENGINE=InnoDB;

CREATE TABLE LIKED_EPISODES (
    UserID INT,
    EpisodeID INT,
    PRIMARY KEY (UserID, EpisodeID),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    FOREIGN KEY (EpisodeID) REFERENCES EPISODES(EpisodeID)
) ENGINE=InnoDB;

CREATE TABLE PLAY_HISTORY (
    HistoryID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    SongID INT,
    PlayedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    FOREIGN KEY (SongID) REFERENCES SONGS(SongID)
) ENGINE=InnoDB;

CREATE TABLE EPISODE_HISTORY (
    HistoryID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    EpisodeID INT,
    PlayedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    FOREIGN KEY (EpisodeID) REFERENCES EPISODES(EpisodeID)
) ENGINE=InnoDB;